### ISSUE TITLE
InventoryProvider / UnityConfig

### ISSUE THREAD

**Issue by jorbor** [gbValant/Inventory#1]
Have not used unity before, but is there a way to remove the static `itemStore` from `InventoryProvider`?

**Comment by gbValant** [comment]
@jorbor, Yes, since the lifetime of these objects is necessarily bound to the lifetime of the application pool for our "in memory" solution, I could also get the same functionality by creating the instance as Unity was initializing and registering it as a singleton with RegisterInstance instead of register type (which I believe has application lifetime as the default lifetime manager, which decides the scope of the registration for injection, but I'd have to double check), from there no other code would have to change because my instance would be used anytime an object expressed a dependency on IInventoryProvider.

If for some reason I needed to support multiple simultaneous inventory providers for different purposes I'd have to use a marker interface or a named registration to distinguish between the two. Sometimes a marker interface is easier and clearer than asking the application to address named dependency registrations.
