### ISSUE TITLE
Different item expiry dates

### ISSUE THREAD

**Issue by jorbor** [gbValant/Inventory#2]
How would you account for multiple items with different expiry dates?

**Comment by gbValant** [comment]
@jorbor, That was a pretty big miss on my part in setting up the data model. This model doesn't support that, but if I had to support that case I would hope there were batches so that I could create a batches relationship and keep my quantity on hand in the batches table in an effort to maintain both clarity and normalization.

For example, InventoryItem would go away and an Item object would hold properties universal to that particular type of item, then a batches table would have columns for the BatchID, ItemID (in our case we were just using the label, which is fine if our scale is small and labels are know unique), ExpireDate, and Quantity on hand. And then ideally whenever an item was pulled from inventory we would pull it from the batch that has the nearest expire date. Even if there weren't batches per se, if the granularity of Expiry were at the day level, then I would create artificial batches for each expiry day per item.
