### ISSUE TITLE
Expiry implementation

### ISSUE THREAD

**Issue by jorbor** [gbValant/Inventory#3]
In the README you mention a couple of options for expiry. Can you pick one and explain how you'd implement it?

**Comment by gbValant** [comment]
@jorbor, I'm thinking for the "in memory" data store assuming an expiry with the day as the granularity, that I would use the Timer class and an injected expiry handler on the provider (since it is currently the repo as well as the provider) and set it to an interval to go off each day very near midnight and perform the necessary notification for the expiration. It would do this with a linq query against current inventory to get all items (batches as I discussed below) expiring the following day (or end of this day depending on how expiry is enforced in the real world) and use that set of results to trigger the notification. An open question would be if notification needed to be sent out per item/batch or if a notification listing the current day's expirations would suffice (this would be driven by the downstream workflow most likely around expirations and how the products exist in the physical world, if at all).
