### ISSUE TITLE
Inventory.RemoveItem

### ISSUE THREAD

**Issue by drewburlingame** [gbValant/Inventory#5]
What status code will the API consumer receive if they delete an item that 
1) doesn't exist?
2) has no 0 quantity?

Is that intended?  What response would you expect an API to return?

**Comment by gbValant** [comment]
Not intentional, didn't get back around to do the try catch over the controller. Currently we'd get a 500, which is not appropriate.

RemoveItem should throw two different exceptions, one for doesn't exist and one for InventoryExhausted so that I could throw appropriate status codes in each case. In my view doesn't exist should be 404 and the 0 count should probably be 408 Conflict (assuming that the caller made the request based on erroneous non-current information at the time they submitted the request).

**Comment by gbValant** [comment]
Oops, 409 Conflict... I was in a conversation earlier today that reminded me that this was 409 rather than 408...
