### ISSUE TITLE
InventoryProvider.Items

### ISSUE THREAD

**Issue by drewburlingame** [gbValant/Inventory#7]
what are the pros/cons of returning a linq iterator?

**Comment by gbValant** [comment]
It's probably a bit bulkier than simply returning an array and it means the consumer needs to have IEnumerable available to it (this is another item where I would have to explicitly check myself against the consumer requirements and confirm the availability of features like Linq and ConcurrentDictionary, availability becoming more of an issue as the .NET ecosystem expands across platforms, etc).

The pros of using the interface instead of a concrete return means I haven't totally pidgeon holed the consumer into a specific IEnumerable implementation, but have set a sort of minimum level of flexibility for them to work with the results if need be.
